name: Deploy Backend to Vercel

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Vercel CLI
        run: npm install -g vercel
        
      - name: Pull Vercel Environment Information
        run: |
          cd backend
          vercel pull --yes --environment=production \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Vercel
        run: |
          cd backend
          vercel --prod \
            --token=${{ secrets.VERCEL_TOKEN }} 